# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# enable bash completion in interactive shells
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# colored prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

# 2013-05-24 Daan - Nieuwe PS1's
if [ "$color_prompt" = yes ]; then
    PS1="$(if [[ ${EUID} == 0 ]]; then echo '\[\033[1;31m\]\u\[\033[01;32m\]@\h'; else echo '\[\033[1;32m\]\u@\h'; fi) \[\033[1;34m\]\w $(if [[ $STY != '' ]]; then echo '\[\033[1;33m\]\$'; else echo '\[\033[1;32m\]\$'; fi)\[\033[00m\] "
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h \w \$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# 2013-10-27 Daan  stel LANG in, zodat deze bak niet om symbolen gaat klagen
LC_ALL=en_US.UTF-8

# start ssh-agent
if [[ $(hostname) == roku ]]; then
	eval $(keychain --eval --quiet)
fi

# 2016-06-18 Daan  liquidprompt instellingen
[[ $- = *i* ]] && source ~/.liquidprompt/liquidprompt

# set gopath
if [[ $(hostname) == roku ]]; then
	export GOPATH=$HOME/Documents/Code/go
	export PATH=$PATH:/usr/lib/go-1.6/bin:$GOPATH/bin
fi

# set clean path
if [[ $(hostname) == roku ]]; then
	export PATH=$HOME/clean/bin:$PATH
fi

# set additional path
export PATH=$HOME/.local/bin:$PATH

# sagemath alias
if [[ $(hostname) == bhava ]]; then
	alias sagemath='docker run --rm -ti --name daan-sagemath sagemath/sagemath'
fi

if [[ $(hostname) == lilo* ]]; then
	export MC=/vol/impuls/marcur
	export PYTHONPATH=$MC/lilo2/lib/python2.6/site-packages
	export PATH=$MC/lilo2/bin:$PATH
	export MANPATH=$MC/lilo2/share/man:$MANPATH
	alias z="exec marietje -H marietje.marie-curie.nl"
fi

# set password store directory
if [[ $(hostname) == roku ]]; then
	export PASSWORD_STORE_DIR=~/Documents/Porno/password-store
fi
