# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=200000

# enable color support of ls and also add handy aliases
alias ls='ls --color=auto'
alias dir='dir --color=auto'
alias vdir='vdir --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# liquidprompt settings
[[ $- = *i* ]] && source ~/.liquidprompt/liquidprompt

# set gopath
if [[ $(hostname) == aang ]]; then
	export GOPATH=$HOME/Documents/Code/go
	export PATH=$PATH:/usr/lib/go-1.6/bin:$GOPATH/bin
fi

# set additional local search path
export PATH=$HOME/.local/bin:$HOME/.cargo/bin:$PATH

# marietje aliases
if [[ $(hostname) == lilo* ]]; then
	export MC=/vol/impuls/marcur
	export PYTHONPATH=$MC/lilo2/lib/python2.6/site-packages
	export PATH=$MC/lilo2/bin:$PATH
	export MANPATH=$MC/lilo2/share/man:$MANPATH
	alias z="exec marietje -H marietje.marie-curie.nl"
	alias n="maruska"
fi

# set password store directory
if [[ $(hostname) == aang ]]; then
	export PASSWORD_STORE_DIR=~/Documents/Vault/password-store
fi

# add an alias for initializing a netsec correction session
if [[ $(hostname) == aang ]]; then
   	alias netsec-correction="wget -q --output-document=/tmp/ta-helpers.sh -- https://gist.githubusercontent.com/dsprenkels/d512dae9f7a4d97bf0d1847918ce17c9/raw/1e66b494b5eceaed66283cea1abc042e0534e12e/ta-helpers.sh && source /tmp/ta-helpers.sh"
fi

# add an alias for starting factorio
if [[ $(hostname) == aang ]]; then
	alias factorio="firejail $HOME/Games/Factorio/bin/x64/factorio"
fi
